# ===================================================================
# Spring Boot configuration.
# ===================================================================

# ===================================================================
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

  
# http server autoconfig
#
server:
  port: 8081
  tomcat:
    uri-encoding: UTF-8

logging:
  config: classpath:config/logback.xml
  level: INFO
  path: ../logs

spring:
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true

swagger:
  enabled: true
  title: pike
  description: pike接口规范
  version: 1.0

jenkins:
  url: http://192.168.199.32:8003
  user: admin
  password: 111111
  
# mybatis config
mybatis:
  configuration:
    logImpl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapperLocations: 
    - classpath*:com/dataman/pike/core/dao/sql/**/*.xml

# druid config
druid:
  monitor:
    enabled: true
  statViewName: DruidStatView
  urlMappings: "/druid/*"
  loginUsername: admin
  loginPassword: 123465
  mergeSql: true
  slowSqlMillis: 3000
  logSlowSql: true
  useGlobalDataSourceStat: false
  
jdbc:
  name: pike
  url: jdbc:mysql://192.168.199.21:3306/pike?useUnicode=true&characterEncoding=UTF-8 
  username: root
  password: jRa4DatfNM7g2
  type: com.alibaba.druid.pool.DruidDataSource
  driverClassName: com.mysql.jdbc.Driver
  initialSize: 5
  minIdle: 5
  maxActive: 20
  maxWait: 60000
  validationQuery: SELECT 1 
  minEvictableIdleTimeMillis: 300000  
  