package com.dataman.pike.core.entity;

import java.util.Date;

public class Project {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_project.id
     *
     * @mbg.generated Wed Oct 25 15:52:22 CST 2017
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_project.exteneral_id
     *
     * @mbg.generated Wed Oct 25 15:52:22 CST 2017
     */
    private Long exteneralId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_project.proname
     *
     * @mbg.generated Wed Oct 25 15:52:22 CST 2017
     */
    private String proname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_project.health_check
     *
     * @mbg.generated Wed Oct 25 15:52:22 CST 2017
     */
    private String healthCheck;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_project.remark_name
     *
     * @mbg.generated Wed Oct 25 15:52:22 CST 2017
     */
    private String remarkName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_project.type
     *
     * @mbg.generated Wed Oct 25 15:52:22 CST 2017
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_project.manager_id
     *
     * @mbg.generated Wed Oct 25 15:52:22 CST 2017
     */
    private Long managerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_project.manager
     *
     * @mbg.generated Wed Oct 25 15:52:22 CST 2017
     */
    private String manager;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_project.phone
     *
     * @mbg.generated Wed Oct 25 15:52:22 CST 2017
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_project.email
     *
     * @mbg.generated Wed Oct 25 15:52:22 CST 2017
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_project.health_status
     *
     * @mbg.generated Wed Oct 25 15:52:22 CST 2017
     */
    private String healthStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_project.create_at
     *
     * @mbg.generated Wed Oct 25 15:52:22 CST 2017
     */
    private Date createAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_project.end_at
     *
     * @mbg.generated Wed Oct 25 15:52:22 CST 2017
     */
    private Date endAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_project.creator
     *
     * @mbg.generated Wed Oct 25 15:52:22 CST 2017
     */
    private Long creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_project.reserve1
     *
     * @mbg.generated Wed Oct 25 15:52:22 CST 2017
     */
    private String reserve1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_project.reserve2
     *
     * @mbg.generated Wed Oct 25 15:52:22 CST 2017
     */
    private String reserve2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_project.reserve3
     *
     * @mbg.generated Wed Oct 25 15:52:22 CST 2017
     */
    private String reserve3;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_project.id
     *
     * @return the value of t_project.id
     *
     * @mbg.generated Wed Oct 25 15:52:22 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_project.id
     *
     * @param id the value for t_project.id
     *
     * @mbg.generated Wed Oct 25 15:52:22 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_project.exteneral_id
     *
     * @return the value of t_project.exteneral_id
     *
     * @mbg.generated Wed Oct 25 15:52:22 CST 2017
     */
    public Long getExteneralId() {
        return exteneralId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_project.exteneral_id
     *
     * @param exteneralId the value for t_project.exteneral_id
     *
     * @mbg.generated Wed Oct 25 15:52:22 CST 2017
     */
    public void setExteneralId(Long exteneralId) {
        this.exteneralId = exteneralId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_project.proname
     *
     * @return the value of t_project.proname
     *
     * @mbg.generated Wed Oct 25 15:52:22 CST 2017
     */
    public String getProname() {
        return proname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_project.proname
     *
     * @param proname the value for t_project.proname
     *
     * @mbg.generated Wed Oct 25 15:52:22 CST 2017
     */
    public void setProname(String proname) {
        this.proname = proname == null ? null : proname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_project.health_check
     *
     * @return the value of t_project.health_check
     *
     * @mbg.generated Wed Oct 25 15:52:22 CST 2017
     */
    public String getHealthCheck() {
        return healthCheck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_project.health_check
     *
     * @param healthCheck the value for t_project.health_check
     *
     * @mbg.generated Wed Oct 25 15:52:22 CST 2017
     */
    public void setHealthCheck(String healthCheck) {
        this.healthCheck = healthCheck == null ? null : healthCheck.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_project.remark_name
     *
     * @return the value of t_project.remark_name
     *
     * @mbg.generated Wed Oct 25 15:52:22 CST 2017
     */
    public String getRemarkName() {
        return remarkName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_project.remark_name
     *
     * @param remarkName the value for t_project.remark_name
     *
     * @mbg.generated Wed Oct 25 15:52:22 CST 2017
     */
    public void setRemarkName(String remarkName) {
        this.remarkName = remarkName == null ? null : remarkName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_project.type
     *
     * @return the value of t_project.type
     *
     * @mbg.generated Wed Oct 25 15:52:22 CST 2017
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_project.type
     *
     * @param type the value for t_project.type
     *
     * @mbg.generated Wed Oct 25 15:52:22 CST 2017
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_project.manager_id
     *
     * @return the value of t_project.manager_id
     *
     * @mbg.generated Wed Oct 25 15:52:22 CST 2017
     */
    public Long getManagerId() {
        return managerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_project.manager_id
     *
     * @param managerId the value for t_project.manager_id
     *
     * @mbg.generated Wed Oct 25 15:52:22 CST 2017
     */
    public void setManagerId(Long managerId) {
        this.managerId = managerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_project.manager
     *
     * @return the value of t_project.manager
     *
     * @mbg.generated Wed Oct 25 15:52:22 CST 2017
     */
    public String getManager() {
        return manager;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_project.manager
     *
     * @param manager the value for t_project.manager
     *
     * @mbg.generated Wed Oct 25 15:52:22 CST 2017
     */
    public void setManager(String manager) {
        this.manager = manager == null ? null : manager.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_project.phone
     *
     * @return the value of t_project.phone
     *
     * @mbg.generated Wed Oct 25 15:52:22 CST 2017
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_project.phone
     *
     * @param phone the value for t_project.phone
     *
     * @mbg.generated Wed Oct 25 15:52:22 CST 2017
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_project.email
     *
     * @return the value of t_project.email
     *
     * @mbg.generated Wed Oct 25 15:52:22 CST 2017
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_project.email
     *
     * @param email the value for t_project.email
     *
     * @mbg.generated Wed Oct 25 15:52:22 CST 2017
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_project.health_status
     *
     * @return the value of t_project.health_status
     *
     * @mbg.generated Wed Oct 25 15:52:22 CST 2017
     */
    public String getHealthStatus() {
        return healthStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_project.health_status
     *
     * @param healthStatus the value for t_project.health_status
     *
     * @mbg.generated Wed Oct 25 15:52:22 CST 2017
     */
    public void setHealthStatus(String healthStatus) {
        this.healthStatus = healthStatus == null ? null : healthStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_project.create_at
     *
     * @return the value of t_project.create_at
     *
     * @mbg.generated Wed Oct 25 15:52:22 CST 2017
     */
    public Date getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_project.create_at
     *
     * @param createAt the value for t_project.create_at
     *
     * @mbg.generated Wed Oct 25 15:52:22 CST 2017
     */
    public void setCreateAt(Date createAt) {
        this.createAt = createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_project.end_at
     *
     * @return the value of t_project.end_at
     *
     * @mbg.generated Wed Oct 25 15:52:22 CST 2017
     */
    public Date getEndAt() {
        return endAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_project.end_at
     *
     * @param endAt the value for t_project.end_at
     *
     * @mbg.generated Wed Oct 25 15:52:22 CST 2017
     */
    public void setEndAt(Date endAt) {
        this.endAt = endAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_project.creator
     *
     * @return the value of t_project.creator
     *
     * @mbg.generated Wed Oct 25 15:52:22 CST 2017
     */
    public Long getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_project.creator
     *
     * @param creator the value for t_project.creator
     *
     * @mbg.generated Wed Oct 25 15:52:22 CST 2017
     */
    public void setCreator(Long creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_project.reserve1
     *
     * @return the value of t_project.reserve1
     *
     * @mbg.generated Wed Oct 25 15:52:22 CST 2017
     */
    public String getReserve1() {
        return reserve1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_project.reserve1
     *
     * @param reserve1 the value for t_project.reserve1
     *
     * @mbg.generated Wed Oct 25 15:52:22 CST 2017
     */
    public void setReserve1(String reserve1) {
        this.reserve1 = reserve1 == null ? null : reserve1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_project.reserve2
     *
     * @return the value of t_project.reserve2
     *
     * @mbg.generated Wed Oct 25 15:52:22 CST 2017
     */
    public String getReserve2() {
        return reserve2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_project.reserve2
     *
     * @param reserve2 the value for t_project.reserve2
     *
     * @mbg.generated Wed Oct 25 15:52:22 CST 2017
     */
    public void setReserve2(String reserve2) {
        this.reserve2 = reserve2 == null ? null : reserve2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_project.reserve3
     *
     * @return the value of t_project.reserve3
     *
     * @mbg.generated Wed Oct 25 15:52:22 CST 2017
     */
    public String getReserve3() {
        return reserve3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_project.reserve3
     *
     * @param reserve3 the value for t_project.reserve3
     *
     * @mbg.generated Wed Oct 25 15:52:22 CST 2017
     */
    public void setReserve3(String reserve3) {
        this.reserve3 = reserve3 == null ? null : reserve3.trim();
    }
}