# ===================================================================
# Spring Boot configuration.
# ===================================================================

# ===================================================================
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

  
# http server autoconfig
#
server:
  port: 8081

logging:
  config: classpath:config/logback.xml
  level: INFO
  path: ../logs


swagger:
  enabled: true
  title: pike
  description: pike接口规范
  version: 1.0

