package com.dataman.pike.core.entity;

import java.util.Date;

public class Dictionary {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dictionary.id
     *
     * @mbg.generated Wed Oct 25 15:52:22 CST 2017
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dictionary.name_cn
     *
     * @mbg.generated Wed Oct 25 15:52:22 CST 2017
     */
    private String nameCn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dictionary.name_en
     *
     * @mbg.generated Wed Oct 25 15:52:22 CST 2017
     */
    private String nameEn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dictionary.type
     *
     * @mbg.generated Wed Oct 25 15:52:22 CST 2017
     */
    private Short type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dictionary.value
     *
     * @mbg.generated Wed Oct 25 15:52:22 CST 2017
     */
    private String value;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dictionary.create_at
     *
     * @mbg.generated Wed Oct 25 15:52:22 CST 2017
     */
    private Date createAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dictionary.update_at
     *
     * @mbg.generated Wed Oct 25 15:52:22 CST 2017
     */
    private Date updateAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dictionary.creator
     *
     * @mbg.generated Wed Oct 25 15:52:22 CST 2017
     */
    private Long creator;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dictionary.id
     *
     * @return the value of t_dictionary.id
     *
     * @mbg.generated Wed Oct 25 15:52:22 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dictionary.id
     *
     * @param id the value for t_dictionary.id
     *
     * @mbg.generated Wed Oct 25 15:52:22 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dictionary.name_cn
     *
     * @return the value of t_dictionary.name_cn
     *
     * @mbg.generated Wed Oct 25 15:52:22 CST 2017
     */
    public String getNameCn() {
        return nameCn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dictionary.name_cn
     *
     * @param nameCn the value for t_dictionary.name_cn
     *
     * @mbg.generated Wed Oct 25 15:52:22 CST 2017
     */
    public void setNameCn(String nameCn) {
        this.nameCn = nameCn == null ? null : nameCn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dictionary.name_en
     *
     * @return the value of t_dictionary.name_en
     *
     * @mbg.generated Wed Oct 25 15:52:22 CST 2017
     */
    public String getNameEn() {
        return nameEn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dictionary.name_en
     *
     * @param nameEn the value for t_dictionary.name_en
     *
     * @mbg.generated Wed Oct 25 15:52:22 CST 2017
     */
    public void setNameEn(String nameEn) {
        this.nameEn = nameEn == null ? null : nameEn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dictionary.type
     *
     * @return the value of t_dictionary.type
     *
     * @mbg.generated Wed Oct 25 15:52:22 CST 2017
     */
    public Short getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dictionary.type
     *
     * @param type the value for t_dictionary.type
     *
     * @mbg.generated Wed Oct 25 15:52:22 CST 2017
     */
    public void setType(Short type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dictionary.value
     *
     * @return the value of t_dictionary.value
     *
     * @mbg.generated Wed Oct 25 15:52:22 CST 2017
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dictionary.value
     *
     * @param value the value for t_dictionary.value
     *
     * @mbg.generated Wed Oct 25 15:52:22 CST 2017
     */
    public void setValue(String value) {
        this.value = value == null ? null : value.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dictionary.create_at
     *
     * @return the value of t_dictionary.create_at
     *
     * @mbg.generated Wed Oct 25 15:52:22 CST 2017
     */
    public Date getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dictionary.create_at
     *
     * @param createAt the value for t_dictionary.create_at
     *
     * @mbg.generated Wed Oct 25 15:52:22 CST 2017
     */
    public void setCreateAt(Date createAt) {
        this.createAt = createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dictionary.update_at
     *
     * @return the value of t_dictionary.update_at
     *
     * @mbg.generated Wed Oct 25 15:52:22 CST 2017
     */
    public Date getUpdateAt() {
        return updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dictionary.update_at
     *
     * @param updateAt the value for t_dictionary.update_at
     *
     * @mbg.generated Wed Oct 25 15:52:22 CST 2017
     */
    public void setUpdateAt(Date updateAt) {
        this.updateAt = updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dictionary.creator
     *
     * @return the value of t_dictionary.creator
     *
     * @mbg.generated Wed Oct 25 15:52:22 CST 2017
     */
    public Long getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dictionary.creator
     *
     * @param creator the value for t_dictionary.creator
     *
     * @mbg.generated Wed Oct 25 15:52:22 CST 2017
     */
    public void setCreator(Long creator) {
        this.creator = creator;
    }
}