package com.dataman.pike.core.entity;

import java.util.Date;

public class Operation {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_operation.id
     *
     * @mbg.generated Wed Oct 25 15:52:22 CST 2017
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_operation.name_cn
     *
     * @mbg.generated Wed Oct 25 15:52:22 CST 2017
     */
    private String nameCn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_operation.name_en
     *
     * @mbg.generated Wed Oct 25 15:52:22 CST 2017
     */
    private String nameEn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_operation.status_
     *
     * @mbg.generated Wed Oct 25 15:52:22 CST 2017
     */
    private Short status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_operation.type
     *
     * @mbg.generated Wed Oct 25 15:52:22 CST 2017
     */
    private Short type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_operation.form_str
     *
     * @mbg.generated Wed Oct 25 15:52:22 CST 2017
     */
    private String formStr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_operation.shell_result_str
     *
     * @mbg.generated Wed Oct 25 15:52:22 CST 2017
     */
    private String shellResultStr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_operation.groovy_result_str
     *
     * @mbg.generated Wed Oct 25 15:52:22 CST 2017
     */
    private String groovyResultStr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_operation.create_at
     *
     * @mbg.generated Wed Oct 25 15:52:22 CST 2017
     */
    private Date createAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_operation.update_at
     *
     * @mbg.generated Wed Oct 25 15:52:22 CST 2017
     */
    private Date updateAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_operation.creator
     *
     * @mbg.generated Wed Oct 25 15:52:22 CST 2017
     */
    private Long creator;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_operation.id
     *
     * @return the value of t_operation.id
     *
     * @mbg.generated Wed Oct 25 15:52:22 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_operation.id
     *
     * @param id the value for t_operation.id
     *
     * @mbg.generated Wed Oct 25 15:52:22 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_operation.name_cn
     *
     * @return the value of t_operation.name_cn
     *
     * @mbg.generated Wed Oct 25 15:52:22 CST 2017
     */
    public String getNameCn() {
        return nameCn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_operation.name_cn
     *
     * @param nameCn the value for t_operation.name_cn
     *
     * @mbg.generated Wed Oct 25 15:52:22 CST 2017
     */
    public void setNameCn(String nameCn) {
        this.nameCn = nameCn == null ? null : nameCn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_operation.name_en
     *
     * @return the value of t_operation.name_en
     *
     * @mbg.generated Wed Oct 25 15:52:22 CST 2017
     */
    public String getNameEn() {
        return nameEn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_operation.name_en
     *
     * @param nameEn the value for t_operation.name_en
     *
     * @mbg.generated Wed Oct 25 15:52:22 CST 2017
     */
    public void setNameEn(String nameEn) {
        this.nameEn = nameEn == null ? null : nameEn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_operation.status_
     *
     * @return the value of t_operation.status_
     *
     * @mbg.generated Wed Oct 25 15:52:22 CST 2017
     */
    public Short getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_operation.status_
     *
     * @param status the value for t_operation.status_
     *
     * @mbg.generated Wed Oct 25 15:52:22 CST 2017
     */
    public void setStatus(Short status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_operation.type
     *
     * @return the value of t_operation.type
     *
     * @mbg.generated Wed Oct 25 15:52:22 CST 2017
     */
    public Short getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_operation.type
     *
     * @param type the value for t_operation.type
     *
     * @mbg.generated Wed Oct 25 15:52:22 CST 2017
     */
    public void setType(Short type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_operation.form_str
     *
     * @return the value of t_operation.form_str
     *
     * @mbg.generated Wed Oct 25 15:52:22 CST 2017
     */
    public String getFormStr() {
        return formStr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_operation.form_str
     *
     * @param formStr the value for t_operation.form_str
     *
     * @mbg.generated Wed Oct 25 15:52:22 CST 2017
     */
    public void setFormStr(String formStr) {
        this.formStr = formStr == null ? null : formStr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_operation.shell_result_str
     *
     * @return the value of t_operation.shell_result_str
     *
     * @mbg.generated Wed Oct 25 15:52:22 CST 2017
     */
    public String getShellResultStr() {
        return shellResultStr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_operation.shell_result_str
     *
     * @param shellResultStr the value for t_operation.shell_result_str
     *
     * @mbg.generated Wed Oct 25 15:52:22 CST 2017
     */
    public void setShellResultStr(String shellResultStr) {
        this.shellResultStr = shellResultStr == null ? null : shellResultStr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_operation.groovy_result_str
     *
     * @return the value of t_operation.groovy_result_str
     *
     * @mbg.generated Wed Oct 25 15:52:22 CST 2017
     */
    public String getGroovyResultStr() {
        return groovyResultStr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_operation.groovy_result_str
     *
     * @param groovyResultStr the value for t_operation.groovy_result_str
     *
     * @mbg.generated Wed Oct 25 15:52:22 CST 2017
     */
    public void setGroovyResultStr(String groovyResultStr) {
        this.groovyResultStr = groovyResultStr == null ? null : groovyResultStr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_operation.create_at
     *
     * @return the value of t_operation.create_at
     *
     * @mbg.generated Wed Oct 25 15:52:22 CST 2017
     */
    public Date getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_operation.create_at
     *
     * @param createAt the value for t_operation.create_at
     *
     * @mbg.generated Wed Oct 25 15:52:22 CST 2017
     */
    public void setCreateAt(Date createAt) {
        this.createAt = createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_operation.update_at
     *
     * @return the value of t_operation.update_at
     *
     * @mbg.generated Wed Oct 25 15:52:22 CST 2017
     */
    public Date getUpdateAt() {
        return updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_operation.update_at
     *
     * @param updateAt the value for t_operation.update_at
     *
     * @mbg.generated Wed Oct 25 15:52:22 CST 2017
     */
    public void setUpdateAt(Date updateAt) {
        this.updateAt = updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_operation.creator
     *
     * @return the value of t_operation.creator
     *
     * @mbg.generated Wed Oct 25 15:52:22 CST 2017
     */
    public Long getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_operation.creator
     *
     * @param creator the value for t_operation.creator
     *
     * @mbg.generated Wed Oct 25 15:52:22 CST 2017
     */
    public void setCreator(Long creator) {
        this.creator = creator;
    }
}