package com.dataman.pike.core.dao.mapper.auto;

import com.dataman.pike.core.entity.FormElement;

public interface FormElementMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_form_element
     *
     * @mbg.generated Mon Oct 30 10:09:22 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_form_element
     *
     * @mbg.generated Mon Oct 30 10:09:22 CST 2017
     */
    int insert(FormElement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_form_element
     *
     * @mbg.generated Mon Oct 30 10:09:22 CST 2017
     */
    int insertSelective(FormElement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_form_element
     *
     * @mbg.generated Mon Oct 30 10:09:22 CST 2017
     */
    FormElement selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_form_element
     *
     * @mbg.generated Mon Oct 30 10:09:22 CST 2017
     */
    int updateByPrimaryKeySelective(FormElement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_form_element
     *
     * @mbg.generated Mon Oct 30 10:09:22 CST 2017
     */
    int updateByPrimaryKey(FormElement record);
}