package com.dataman.pike.core.dao.auto.mapper;

import com.dataman.pike.core.entity.FormElement;

public interface FormElementMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_form_element
     *
     * @mbg.generated Wed Oct 25 15:52:22 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_form_element
     *
     * @mbg.generated Wed Oct 25 15:52:22 CST 2017
     */
    int insert(FormElement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_form_element
     *
     * @mbg.generated Wed Oct 25 15:52:22 CST 2017
     */
    int insertSelective(FormElement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_form_element
     *
     * @mbg.generated Wed Oct 25 15:52:22 CST 2017
     */
    FormElement selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_form_element
     *
     * @mbg.generated Wed Oct 25 15:52:22 CST 2017
     */
    int updateByPrimaryKeySelective(FormElement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_form_element
     *
     * @mbg.generated Wed Oct 25 15:52:22 CST 2017
     */
    int updateByPrimaryKey(FormElement record);
}