package com.dataman.pike.core.dao.auto.mapper;

import com.dataman.pike.core.entity.Operation;

public interface OperationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operation
     *
     * @mbg.generated Wed Oct 25 15:52:22 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operation
     *
     * @mbg.generated Wed Oct 25 15:52:22 CST 2017
     */
    int insert(Operation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operation
     *
     * @mbg.generated Wed Oct 25 15:52:22 CST 2017
     */
    int insertSelective(Operation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operation
     *
     * @mbg.generated Wed Oct 25 15:52:22 CST 2017
     */
    Operation selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operation
     *
     * @mbg.generated Wed Oct 25 15:52:22 CST 2017
     */
    int updateByPrimaryKeySelective(Operation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operation
     *
     * @mbg.generated Wed Oct 25 15:52:22 CST 2017
     */
    int updateByPrimaryKey(Operation record);
}