package com.dataman.pike.core.dao.auto.mapper;

import com.dataman.pike.core.entity.Project;

public interface ProjectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project
     *
     * @mbg.generated Wed Oct 25 15:52:22 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project
     *
     * @mbg.generated Wed Oct 25 15:52:22 CST 2017
     */
    int insert(Project record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project
     *
     * @mbg.generated Wed Oct 25 15:52:22 CST 2017
     */
    int insertSelective(Project record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project
     *
     * @mbg.generated Wed Oct 25 15:52:22 CST 2017
     */
    Project selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project
     *
     * @mbg.generated Wed Oct 25 15:52:22 CST 2017
     */
    int updateByPrimaryKeySelective(Project record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project
     *
     * @mbg.generated Wed Oct 25 15:52:22 CST 2017
     */
    int updateByPrimaryKey(Project record);
}